<a href="https://colab.research.google.com/github/scaryundead007/car_price_predictor/blob/master/Last_try_ALA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def transpose(matrix):
    rows = len(matrix)
    columns = len(matrix[0])

    matrix_T = []
    for j in range(columns):
        row = []
        for i in range(rows):
           row.append(matrix[i][j])
        matrix_T.append(row)

    return matrix_T

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Cleaned_CarData.csv')


In [4]:
df.drop('Unnamed: 0',axis = 1,inplace = True)
df.head()

name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [5]:
columns_titles = ["name","company","year","kms_driven","fuel_type","Price"]
df=df.reindex(columns=columns_titles)
df

name   company  year  kms_driven fuel_type   Price
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol   80000
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel  425000
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol  325000
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel  575000
4                 Ford Figo      Ford  2012       41000    Diesel  175000
..                      ...       ...   ...         ...       ...     ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol  270000
811          Tata Indica V2      Tata  2009       30000    Diesel  110000
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol  300000
813            Tata Zest XM      Tata  2018       27000    Diesel  260000
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel  390000

[815 rows x 6 columns]

In [6]:
arr1 = df['fuel_type'].unique()
for j in range(len(arr1)):
  df['fuel_type'] = df['fuel_type'].str.replace(arr1[j],str(j+1))

In [7]:
arr = df['company'].unique()
for i in range(len(arr)):
  df['company'] = df['company'].str.replace(arr[i],str(i+1))

In [8]:
df['fuel_type'] = df['fuel_type'].astype('float')
df['company'] = df['company'].astype('float')
df['year'] = df['year'].astype('float')
df['kms_driven'] = df['kms_driven'].astype('float')
df['Price'] = df['Price'].astype('float')


In [9]:
df.dtypes

name           object
company       float64
year          float64
kms_driven    float64
fuel_type     float64
Price         float64
dtype: object

In [11]:
#Converting from pandas.core.frame.DataFrame to numpy.ndarray
train = df.values



In [12]:
test = train[400:,:]

In [13]:
test

array([['Renault Duster 85', 0.32, 0.9980188211986132, 0.1625,
        0.6666666666666666, 0.2306451612903226],
       ['Hyundai Grand i10', 0.04, 0.9975235264982665, 0.0875,
        0.3333333333333333, 0.10967741935483871],
       ['Honda Brio V', 0.36, 0.9965329370975731, 0.0825,
        0.3333333333333333, 0.07580645161290323],
       ...,
       ['Toyota Corolla Altis', 0.28, 0.995047052996533, 0.33,
        0.3333333333333333, 0.0967741935483871],
       ['Tata Zest XM', 0.48, 0.9995047052996533, 0.0675,
        0.6666666666666666, 0.08387096774193549],
       ['Mahindra Quanto C8', 0.08, 0.9970282317979198, 0.1,
        0.6666666666666666, 0.12580645161290321]], dtype=object)

In [14]:
X_train = train[:, 1:-1]
y_train = train[:,-1]

X_test = test[:,1:-1]
y_test = test[:,-1]

In [15]:
y_train

array([0.025806451612903226, 0.13709677419354838, 0.10483870967741936,
       0.18548387096774194, 0.056451612903225805, 0.06129032258064516,
       0.267741935483871, 0.08064516129032258, 0.05870967741935484,
       0.10161290322580645, 0.1338709677419355, 0.1032258064516129,
       0.025806451612903226, 0.13709677419354838, 0.3225806451612903,
       0.16129032258064516, 0.11290322580645161, 0.05161290322580645,
       0.11290322580645161, 0.1, 0.024193548387096774,
       0.03225806451612903, 0.03225806451612903, 0.03225806451612903,
       0.06129032258064516, 0.0935483870967742, 0.03064516129032258,
       0.05806451612903226, 0.12419354838709677, 0.08064516129032258,
       0.05806451612903226, 0.03387096774193549, 0.03387096774193549,
       0.20967741935483872, 0.22258032258064517, 0.14451612903225808,
       0.17709677419354838, 0.16161290322580646, 0.1580641935483871,
       0.09032258064516129, 0.08064516129032258, 0.11290290322580646,
       0.09193516129032259, 0.111290322

In [16]:
X_train.shape[0]

815

In [17]:
x_bias = np.ones((X_train.shape[0],1))
X_train = np.append(x_bias,X_train,axis=1)
X_train = np.array(X_train, dtype=np.float)


In [18]:
#For testing set
x_bias = np.ones((X_test.shape[0],1))
X_test = np.append(x_bias,X_test,axis=1)
X_test = np.array(X_test, dtype=np.float)

In [19]:
x_transpose = np.transpose(X_train)


In [20]:
x_transpose_dot_x = x_transpose.dot(X_train)


In [21]:
var1 = np.linalg.inv(x_transpose_dot_x)
var1

array([[ 3.53736424e+02,  1.66979990e-02, -3.55153352e+02,
        -2.55414299e+00,  1.12945803e+00],
       [ 1.66979990e-02,  3.26454494e-02, -2.21614170e-02,
        -6.04850482e-03, -3.69064515e-03],
       [-3.55153352e+02, -2.21614170e-02,  3.56589086e+02,
         2.55703910e+00, -1.15368076e+00],
       [-2.55414299e+00, -6.04850482e-03,  2.55703910e+00,
         2.00079430e-01, -3.30483643e-02],
       [ 1.12945803e+00, -3.69064515e-03, -1.15368076e+00,
        -3.30483643e-02,  5.11612032e-02]])

In [22]:
#X transpose dot y vector
var2 = x_transpose.dot(y_train)

In [23]:
theta = var1.dot(var2)
theta

array([-17.08040351607623, 0.12493606991230616, 17.197993385117314,
       -0.2216475165410876, 0.12844507218801526], dtype=object)

In [24]:
predicted_values = np.dot(X_test,theta)
predicted_values = abs(predicted_values)

In [25]:
mean = np.mean(y_test)

In [26]:
R2_score = 1 - np.sum((predicted_values-y_test)**2)/np.sum((y_test-mean)**2)
print(R2_score)

0.21372209404684972
